### PR TITLE
Add avogadro-number and correct kg-amu

### PR DESCRIPTION
**Pull request by afresh1**
# Pull request template for `Math::Constants`

## What kind of constants are you adding and its origin

Not actually _adding_ any, just correcting (I think) some names.  I did talk to a friend who is more familiar with chemistry and such but didn't grok what they explained.

I'm fairly sure this is correct, based on what I read on Wikipedia and the other places on the Internet, but it's super confusing as Avogadro's constant seems to be a mole, but it's expressed in reciprocal moles.  It seems like using it makes sense, but talking about it is confusing.

https://en.wikipedia.org/wiki/2019_redefinition_of_SI_base_units#Mole
https://en.wikipedia.org/wiki/Unified_atomic_mass_unit
https://en.wikipedia.org/wiki/Avogadro_constant

I did remove the "L" short name, as that again is Avogadro's constant which includes units we don't have, but did not add "N" or "N₀" as I wasn't sure which to choose.

I'm also fairly sure that a g/amu is equal to Avogadro's number, while a kilogram is 1000 grams.  But, I didn't really find a good reference on that.

## Check list

* [x] It's a well known constant and I have added a reference for it
* [x] I have added a test and it works.
* [x] I'm using the usual naming and abbreviation conventions.

### CODE REVIEW

**Review by JJ — APPROVED** [review]
Thanks a lot! Great work.

**Comment by librasteve** [comment]
@afresh1 , this looks cool! I have a couple of comments:

- if you want units, you can use [Physics::Constants](https://github.com/p6steve/raku-Physics-Constants.git) which integrates this module with [Physics::Unit](https://github.com/p6steve/raku-Physics-Unit) and [Physics::Measure](https://github.com/p6steve/raku-Physics-Measure)
- I am working on Physics::Error which hopefully should give a nice way to bring the accuracy of physical constants into play

Any feedback, PRs etc over there also welcome!

---

Update 1

Looks like Physics::Constants work on local machine test, but Travis / Docker build is failing ... so please ignore Travis status for now.

**Comment by kjpye** [comment]
Steve,

[Not replying all because this is peripheral at best to the issue under
discussion.]

I've been working off and on on a major upgrade to Math::Constants which
adds all sorts of things, but I'm not sure that most of those changes
belong in Math::Constants. This includes

1. Adding everything from the CODATA, not just the limited version which is
in Math::Constants;
2. Adding the information from CODATA such as the error bounds and units
3. Calculating values of derived constants rather than using the truncated
values in the original data, which gives better accuracy and precision;
while
4. maintaining full compatibility with what is already there,

I started working on this before you published Physics::Constants, but
there is a lot of commonality in our approaches with similar looking
objects defined.

My current preferred approach would be to leave Math::Constants more or
less as it is, and incorporate this into a module called something like
Physics Constants :-)

Would you be interested in patches to Physics::Constants which added that
sort of information directly, and removed the dependency on Math::Constants?

I'd need to do some work to add some of the things which are missing at the
moment like the various arrays and hashes of names, but that could be done
without too much trouble.

You can see where I'm at at github.com/kjpye/raku-math-constants

Kevin.

**Comment by librasteve** [comment]
Hi Kevin

Really appreciate the email. That’s a really cool extension. I am all for working collaboratively since my tuits are limited and definitely would be happy to work together.

I’m on the hop right now, but off the top of my head, I would say that instead of (in addition to?) applying units as Str in the new Math::Constants as you are doing, you could use my Physics::Unit / Physics::Measure modules to apply units as Objects in a coherent Class framework.

I have just started work on Physics::Error.

Do take a look at my repos in GitHub and let me know your thoughts…

https://github.com/p6steve/raku-Physics-Unit <https://github.com/p6steve/raku-Physics-Unit>
https://github.com/p6steve/raku-Physics-Measure <https://github.com/p6steve/raku-Physics-Measure>
https://github.com/p6steve/raku-Physics-Constants <https://github.com/p6steve/raku-Physics-Constants> 

Physics::Constants is currently intended to just wrap Math::Constants - I wanted to avoid having different versions of the truth. Possibly we could say that Math::Constants stays as is (so you can either use it standalone) and we update Physics::Constants to align to your unit specs (and errors) and keep it as a more full fat wrapper that works with Physics::Measure … ???

So yes CODATA as the definitive source is cool and I am sure we can define a common approach.

~p6steve

**Comment by afresh1** [comment]
Sounds like an exciting future! I look forward to it all coming together.  I still don't understand what a kg-amu is though :-)

**Pull request merged**
